### ISSUE TITLE
onload function never called

### ISSUE THREAD

**Issue by kburkettgeo** [davidpadbury/node-highcharts#8]
i'm trying to create a simple mocha test to execute the beginner example:

![image](https://cloud.githubusercontent.com/assets/3661273/3577871/bd528974-0ba1-11e4-8327-2267820f4f61.png)

now, from node-highcharts.js:

![image](https://cloud.githubusercontent.com/assets/3661273/3577840/50a76736-0ba1-11e4-8504-b0895e8ac26a.png)

the highlighted code is never reached.  any ideas?

**Comment by davidpadbury** [comment]
Hi @kburkettgeo, I'm afraid most of the libraries involved in this experiment are now several years out of date so I'd expect all manor of problems. Please see [Highchart's recommendations](http://www.highcharts.com/component/content/article/2-news/52-serverside-generated-charts) for generating charts entirely on the server.

**Comment by mringwal** [comment]
I've tried this experiment a few years ago. Unfortunately, some labels get misplaced and I had no idea how to fix it. Using phantomJS as suggested by Highcharts works well on our server, but the node version is much faster. Thanks @davidpadbury for this experiment: do you wanna a give it a new try, maybe some of the used libraries got updated? :)

**Comment by davidpadbury** [comment]
I think the challenge (as mentioned in their own post), is the lack of box model dimensions in zombie.

Could give it another bash. I'd just start again from scratch.
